enum color_t {BLACK, RED, BLUE};
enum bumper_t {NONE, FRONT, RIGHT, LEFT, BACK};
enum state_t {START_STATE, LINE_FOLLOW_STATE, LINE_SEARCH_STATE, FIRST_BUMP_STATE};
enum search_state_t {START, PIVOT_LEFT, PIVOT_RIGHT, PIVOT_TO_ORIG_POS, REVERSE, DONE};

